# bin keys
NAME = "name"
URL = "url"
AUTHOR = "author"
VERSION = "version"
COMMENT = "comment"

FETCHER = "fetcher"
PARSER = "parser"

ENDPOINTS = "endpoints"
ENDPOINT_PATH = "path"
FIELDS = "fields"
FIELD_SELECT = "select"
FIELD_SELECT_CSS = "css"
FIELD_EXTRACT = "extract"
FIELD_EXTRACT_INNER_TEXT = "text"
FIELD_EXTRACT_ATTRIBUTE = "attr"
FIELD_TYPE = "type"
FIELD_TYPE_STRING = "string"
FIELD_TYPE_INT = "int"
FIELD_TYPE_FLOAT = "float"