DEFAULT_FETCHER = "bs4"
DEFAULT_PARSER = "playwright"

BAG_FIELD_PARAMS = "params"
BAG_FIELD_URL = "url"
BAG_FIELD_HTML = "html"
BAG_FIELD_DATA = "data"
BAG_FIELD_TIMESTAMP ="timestamp"

NEST_PATH = "src/raccoonz/nest"
NEST_PATH_RAW = "raw"
NEST_PATH_DATA = "data"

PLAYWRIGHT_TIMEOUT = 10000
PLAYWRIGHT_HEADLESS = True
PLAYWRIGHT_CONTEXT_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
PLAYWRIGHT_CONTEXT_LOCALE = "en-US"
PLAYWRIGHT_EXTRA_HTTP_HEADERS = {"Accept-Language": "en-US,en;q=0.9"}
PLAYWRIGHT_PAGE_WAIT_UNTIL = "domcontentloaded"
PLAYWRIGHT_PAGE_TIMEOUT = 3000

REQUESTS_TIMEOUT = 10
REQUESTS_HEADERS_USER_AGENT = "Mozilla/5.0 (Windows NT 10/0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
REQUESTS_HEADERS_ACCEPT = "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
REQUESTS_HEADERS_ACCEPT_LANGUAGE = "en-US,en;q=0.9"
REQUESTS_HEADERS_ACCEPT_ENCODING = "gzip, deflate, br"
REQUESTS_HEADERS_CONNECTION = "keep-alive"
REQUESTS_HEADERS_UPGRADE_INSECURE_REQUESTS = "1"
REQUESTS_HEADERS_REFERER = "https://www.google.com/"
REQUESTS_HEADERS_DNT = "1"

RESULT_ERRORS = "_errors"