DEFAULT_FETCHER = "bs4"
DEFAULT_PARSER = "playwright"

BAG_FIELD_PARAMS = "params"
BAG_FIELD_URL = "url"
BAG_FIELD_HTML = "html"
BAG_FIELD_DATA = "data"
BAG_FIELD_TIMESTAMP ="timestamp"

NEST_PATH = "src/raccoonz/nest"
NEST_PATH_RAW = "raw"
NEST_PATH_DATA = "data"

PLAYWRIGHT_TIMEOUT = 10000
PLAYWRIGHT_HEADLESS = True
PLAYWRIGHT_CONTEXT_USER_AGENT = "Mozilla/5.0 (Windows NT 10/0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
PLAYWRIGHT_CONTEXT_LOCALE = "en-US"
PLAYWRIGHT_EXTRA_HTTP_HEADERS = {"Accept-Language": "en-US,en;q=0.9"}
PLAYWRIGHT_PAGE_WAIT_UNTIL = "domcontentloaded"
PLAYWRIGHT_PAGE_TIMEOUT = 3000

REQUESTS_TIMEOUT = 10
REQUESTS_USER_AGENT = "Mozilla/5.0"
REQUESTS_ACCEPT_LANGUAGE = "en-US,en;q=0.9"